[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-snapmock"
dynamic = ["version"]
classifiers = [
    "Framework :: Pytest",
]

[project.entry-points.pytest11]
myproject = "pytest_snapmock.plugin"
